name: Auto Update & Push Playlist

on:
  schedule:
    - cron: '0 */24 * * *'  # Runs every 6 hours
  workflow_dispatch:       # Allows manual trigger

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.FILE_APIAGTN }}
      run: unzip -P "$ZIP_PASS" angt.zip

    - name: Run Python script
      run: python angt.zip

    - name: Delete script after running
      if: always()
      run: rm -f angt.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

    - name: Copy playlist to target repository
      run: cp *.m3u ${{ secrets.TARGET_NAME }}/

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAME }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add *.m3u
        git commit -m "🔄 Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
