name: Merge M3U Playlists

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests jq

      - name: Download External Repos
        run: |
          echo "Cloning source repositories..."
          git clone --depth=1 https://${{ secrets.SOURCE_URL1 }} temp1
          git clone --depth=1 https://${{ secrets.SOURCE_URL2 }} temp2
          mkdir -p merged
          cp -r temp1/*.m3u merged/ || true
          cp -r temp1/*.m3u8 merged/ || true
          cp -r temp2/*.m3u merged/ || true
          cp -r temp2/*.m3u8 merged/ || true
          cp -r ./*.m3u merged/ || true
          cp -r ./*.m3u8 merged/ || true

          # Download new external playlist (always included as-is)
          echo "Downloading external playlist (New-Best)..."
          curl -L "${{ secrets.External_source }}" -o merged/New-Best.m3u

      - name: Download & Process Config JSON
        run: |
          echo "${{ secrets.PLAYLIST_CONFIG_JSON }}" > config.json
          echo "Config JSON written."

          mkdir -p merged/joined

          # Handle Join entries
          jq -c '.Join[]' config.json | while read entry; do
            NAME=$(echo "$entry" | jq -r '.Name')
            URL=$(echo "$entry" | jq -r '.Url')
            CHANGE=$(echo "$entry" | jq -r '.["group name change"]')
            FILE="merged/joined/${NAME// /_}.m3u"

            echo "Downloading join playlist: $NAME from $URL"
            curl -L "$URL" -o "$FILE"

            if [ "$CHANGE" = "yes" ]; then
              awk -v fname="$NAME" '
                /^#EXTINF/ {
                  if (match($0, /group-title="[^"]*"/)) {
                    oldgroup = substr($0, RSTART+13, RLENGTH-14)
                    sub(/group-title="[^"]*"/, "group-title=\"" fname " | " oldgroup "\"")
                    print
                  } else {
                    sub(/^#EXTINF:/, "#EXTINF: group-title=\"" fname "\" ,")
                    print
                  }
                  next
                }
                { print }
              ' "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
            fi
          done

      - name: Merge Playlists
        run: |
          echo "#EXTM3U" > All-playlist.m3u

          # Read skip list into a bash array
          mapfile -t SKIP_FILES < <(jq -r '.Skip[].file' config.json)

          should_skip() {
            local f=$1
            for s in "${SKIP_FILES[@]}"; do
              if [ "$s" = "$f" ]; then
                return 0
              fi
            done
            return 1
          }

          for f in merged/*.m3u merged/*.m3u8 merged/joined/*.m3u; do
            [ -f "$f" ] || continue
            fname=$(basename "$f")

            if should_skip "$fname"; then
              echo "Skipping $fname (from config)"
              continue
            fi

            fname_noext="${fname%.*}"

            # Special case: keep New-Best.m3u exactly as-is
            if [ "$fname" = "New-Best.m3u" ]; then
              awk 'NR>1 {print}' "$f" >> All-playlist.m3u
              continue
            fi

            # Default handling
            awk -v fname="$fname_noext" '
              /^#EXTINF/ {
                if (match($0, /group-title="[^"]*"/)) {
                  oldgroup = substr($0, RSTART+13, RLENGTH-14)
                  sub(/group-title="[^"]*"/, "group-title=\"" fname " | " oldgroup "\"")
                  print
                } else {
                  sub(/^#EXTINF:/, "#EXTINF: group-title=\"" fname "\" ,")
                  print
                }
                next
              }
              { print }
            ' "$f" >> All-playlist.m3u
          done

      - name: Clone target private repository
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

      - name: Copy playlist to target repository
        run: cp All-playlist.m3u ${{ secrets.TARGET_NAME }}/All-playlist.m3u

      - name: Commit & push to target repository
        run: |
          cd ${{ secrets.TARGET_NAME }}
          git config user.name "${{ secrets.TARGET_REPO_USER }}"
          git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
          git add All-playlist.m3u
          git commit -m "🔄 Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
