name: Auto Update & Push Playlist

on:
  schedule:
    - cron: '0 */1 * * *'    
  workflow_dispatch:         

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Initial 1 minute delay before starting
      run: sleep 70

    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILEAZ }}
      run: unzip -o -P "$ZIP_PASS" az.zip

    - name: Run Python script
      run: python az.py

    - name: Delete script after running
      if: always()  # Always run even if previous step fails
      run: rm -f az.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

    - name: Copy playlist to target repository
      run: cp z5.m3u ${{ secrets.TARGET_NAME }}/z5.m3u

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAME }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add z5.m3u
        git commit -m "🔄 Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
