name: Auto Update Playlist

on:
  schedule:
    - cron: '*/40 * * * *'  # Every 30 hours
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: |
          python -m pip install --upgrade pip
          pip install playwright requests pytz
          playwright install chromium --with-deps

    - name: Create fld
      run: mkdir tmp_folder

    - name: Unp
      env:
        FILE_API: ${{ secrets.FILE_APISCHS2_WAY2 }}
      run: |
        unzip -o -P "$FILE_API" code-1-w2.zip -d tmp_folder

    - name: Rps
      run: python3 tmp_folder/code.py

    - name: DARS
      if: always()
      run: rm -rf tmp_folder

    - name: Clone target Repo
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKENCHS1 }}@${{ secrets.TARGET_URLTSCHD1 }} ${{ secrets.TARGET_NAMETSCHD1 }}

    - name: Copy target repo
      run: |
        cp *.m3u ${{ secrets.TARGET_NAMETSCHD1 }}/ || true

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMETSCHD1 }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m " Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
