name: hi

on:
  schedule:
    - cron: '*/9 * * * *'  # f
  workflow_dispatch:

jobs:
  post-streams:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      # Step 4: Unzip protected Python script
      - name: Unzip protected Python script
        env:
          ZIP_PASS: ${{ secrets.ZIP_PASSTG }}
        run: unzip -o -P "$ZIP_PASS" ftgs.zip

      # Step 5: Run Python script
      - name: Run Python script
        run: python ftgs.py

      # Step 6: Cleanup files
      - name: Cleanup files
        if: always()
        run: rm -f ftgs.py
