name: Auto Update & Push Playlist

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Initial delay (optional)
      run: sleep 10

    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Fetch Playlist from Secret URL
      env:
        PLAYLIST_URL: ${{ secrets.JTV }}
      run: |
        curl -L "$PLAYLIST_URL" -o Jtv.m3u

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

    - name: Copy playlist to target repository
      run: cp Jtv.m3u ${{ secrets.TARGET_NAME }}/Jtv.m3u

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAME }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add Jtv.m3u
        git commit -m "🔄 Auto update BDIX1 playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
