name: Auto Update & Push Playlist

on:
  schedule:
    - cron: '0 */4 * * *'  # Runs every 4 hours
  workflow_dispatch:       # Allows

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip install requests

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZI_FILE3 }}
      run: unzip -P "$ZIP_PASS" otv2.zip

    - name: Run Python script
      run: python otv2.py

    - name: Delete script after running
      if: always()  # Always run this step even if previous step fails
      run: rm -f otv2.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2 }}@${{ secrets.TARGET_URL }} ${{ secrets.TARGET_NAME }}

    - name: Copy playlist to target repository
      run: cp movie-playlist.m3u ${{ secrets.TARGET_NAME }}/

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAME }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add movie-playlist.m3u
        git commit -m "🔄 Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
