name: Auto Update & Push Playlist

on:
  schedule:
    - cron: '*/25 * * * *'  # Runs every 1 hour
  workflow_dispatch:

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install Python dependencies
      run: pip install requests pytz pycryptodome

    - name: Unzip protected Python script
      env:
        ZIP_PASS: ${{ secrets.ZIP_FILET }}
      run: unzip -o -P "$ZIP_PASS" t.zip

    - name: Run Python script
      run: python t.py

    - name: Delete script after running
      if: always()
      run: rm -f t.py

    - name: Clone target private repository
      run: |
        git clone https://x-access-token:${{ secrets.TARGET_TOKEN2TS }}@${{ secrets.TARGET_URLTS }} ${{ secrets.TARGET_NAMETS }}

    - name: Copy selected playlist files to target repository
      run: |
        cp channels_data.json ${{ secrets.TARGET_NAMETS }}/channels_data.json
        cp ns_player.m3u ${{ secrets.TARGET_NAMETS }}/ns_player.m3u
        cp ott_navigator.m3u ${{ secrets.TARGET_NAMETS }}/ott_navigator.m3u
        cp universal_player.m3u ${{ secrets.TARGET_NAMETS }}/universal_player.m3u

    - name: Commit & push to target repository
      run: |
        cd ${{ secrets.TARGET_NAMETS }}
        git config user.name "${{ secrets.TARGET_REPO_USER }}"
        git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
        git add .
        git commit -m "🔄 Auto update playlist on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
        git push
