name: Auto Update 1

on:
  schedule:
    - cron: '*/25 * * * *'  # Every 25 minutes
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} test.zip

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        if: always()
        run: rm -f run.py

      # ⛔️ REMOVE source commit step
      # - name: Commit Changes
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add playlist.m3u
      #     git diff --quiet && git diff --staged --quiet || git commit -m "Auto update playlist.m3u"

      # ⛔️ REMOVE Push to source
      # - name: Push Changes to Source Repo
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: main

      - name: Clone Target Repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@${{ secrets.TARGET_REPO_URL }} ${{ secrets.TARGET_REPO_NAME }}

      - name: Copy Files to Target Repo
        run: |
          cp playlist.m3u ${{ secrets.TARGET_REPO_NAME }}/

      - name: Commit & Push to Target Repo
        run: |
          cd ${{ secrets.TARGET_REPO_NAME }}
          git config user.name "${{ secrets.TARGET_REPO_USER }}"
          git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
          git add .
          git commit -m "Synced playlist.m3u from source on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
