name: Auto Update 1

on:
  schedule:
    - cron: '*/40 * * * *'  # Every 40 minutes
  workflow_dispatch:

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Unzip Protected Script
        run: unzip -P ${{ secrets.ZIP_PASSWORD2 }} test.zip

      - name: Run Python Script
        run: python run.py

      - name: Delete Script After Run
        if: always()
        run: rm -f run.py

      
      - name: Clone Target Repo
        run: |
          git clone https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@${{ secrets.TARGET_REPO_URL }} ${{ secrets.TARGET_REPO_NAME }}

      
      - name: Copy Files to Target Repo
        run: |
          cp playlist.m3u ${{ secrets.TARGET_REPO_NAME }}/

      
      - name: Commit & Push to Target Repo
        run: |
          cd ${{ secrets.TARGET_REPO_NAME }}
          git config user.name "${{ secrets.TARGET_REPO_USER }}"
          git config user.email "${{ secrets.TARGET_REPO_USER }}@users.noreply.github.com"
          git add .
          git commit -m "Synced playlist.m3u from source on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push

      
      - name: Update README in Source Repo
        run: |
          echo "✅ Hi Complete – Synced on $(date '+%Y-%m-%d %H:%M:%S')" >> README.md

      - name: Commit README Update
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Updated README with sync status" || echo "No changes"
          git push
